version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres.islom_1228
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  express:
    image: node:14
    container_name: express_server
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres.islom_1228
      PGDATABASE: postgres
      PGPORT: "5432"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    command: npm start

volumes:
  postgres_data:
